# Generated by Django 4.0.4 on 2022-05-28 13:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('content', wagtail.fields.StreamField([('field1', wagtail.blocks.CharBlock()), ('quote', wagtail.blocks.StructBlock([('quote_content', wagtail.blocks.CharBlock()), ('person', wagtail.blocks.CharBlock()), ('random_id', wagtail.blocks.IntegerBlock(required=False))])), ('date', wagtail.blocks.DateTimeBlock()), ('someblock', wagtail.blocks.StructBlock([('random_content', wagtail.blocks.CharBlock()), ('random_date', wagtail.blocks.DateBlock(required=False))]))], use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
