# Generated by Django 4.0.5 on 2022-06-16 06:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('field1', wagtail.blocks.CharBlock()), ('quote', wagtail.blocks.StructBlock([('quote_content', wagtail.blocks.CharBlock()), ('author', wagtail.blocks.CharBlock()), ('random_id', wagtail.blocks.IntegerBlock(required=False))])), ('date', wagtail.blocks.DateTimeBlock()), ('someblock', wagtail.blocks.StructBlock([('random_content', wagtail.blocks.CharBlock()), ('random_date', wagtail.blocks.DateBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
