# Generated by Django 4.0.5 on 2022-07-17 12:41

from django.db import migrations
from wagtail_streamfield_migration_toolkit.funcs import migrate_stream_data
from wagtail_streamfield_migration_toolkit.operations import RenameStreamChildrenOperation

def forward(apps, schema_editor):
    migrate_stream_data(
        apps=apps,
        schema_editor=schema_editor,
        app_name="blog",
        model_name="BlogPage",
        field_name="content",
        block_path_str="field1",
        operation=RenameStreamChildrenOperation(new_name="block1"),
        with_revisions=True,
        revision_limit=1,
        chunk_size=1024
    )

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_content'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
