# Generated by Django 4.0.3 on 2022-07-24 15:45

from django.db import migrations
import datetime

from wagtail_streamfield_migration_toolkit.funcs import MigrateStreamData
from wagtail_streamfield_migration_toolkit.operations import (
    RenameStreamChildrenOperation,
    RenameStructChildrenOperation,
)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpage_content_and_more'),
    ]

    operations = [
        MigrateStreamData(
            app_name="blog",
            model_name="BlogPage",
            field_name="content",
            operations_and_block_paths=[
                (RenameStreamChildrenOperation(new_name="block1"), "field1"),
                (RenameStructChildrenOperation(new_name="author"), "quote.person")
            ]
            revisions_from=datetime.date(2022, 7, 24)
        ),
        MigrateStreamData(
            app_name="blog",
            model_name="SampleModel",
            field_name="stream_content",
            operations_and_block_paths=[
                (RenameStreamChildrenOperation(new_name="block1"), "field1"),
                (RenameStructChildrenOperation(new_name="author"), "quote.person")
            ]
            revisions_from=datetime.date(2022, 7, 24)
        ),
        MigrateStreamData(
            app_name="blog",
            model_name="SampleModelWithRevisions",
            field_name="stream_content",
            operations_and_block_paths=[
                (RenameStreamChildrenOperation(new_name="block1"), "field1"),
                (RenameStructChildrenOperation(new_name="author"), "quote.person")
            ]
            revisions_from=datetime.date(2022, 7, 24)
        )
    ]
